services:
  authentication:
    build: .
    container_name: authentication
    ports:
      - "${PORT}:8080"
    environment:
      - PORT=8080
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB:-auth_db}
      - DB_SSLMODE=disable
    labels:
      traefik.enable: "true"
      traefik.http.routers.auth.rule: "Host(`dev-api.bikes2road.com`) && PathPrefix(`/api/auth`)"
      traefik.http.routers.auth.entrypoints: "web,websecure"
      traefik.http.routers.auth.tls: "true"
      traefik.http.routers.auth.tls.certresolver: "letsencrypt"
      traefik.http.services.auth.loadbalancer.server.port: "8080"
      traefik.http.middlewares.auth-strip.stripprefix.prefixes: "/api/auth"
      traefik.http.routers.auth.middlewares: "auth-strip"

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true