services:
  authentication-prod:
    build: .
    container_name: authentication-prod
    ports:
      - "${PORT}:8080"
    environment:
      - PORT=8080
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - USERS_SERVICE_URL=${USERS_SERVICE_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    labels:
      traefik.enable: "true"
      traefik.http.routers.authentication-prod.rule: "Host(`${DOMAIN}`) && PathPrefix(`/api/auth`)"
      traefik.http.routers.authentication-prod.entrypoints: "web,websecure"
      traefik.http.routers.authentication-prod.tls: "true"
      traefik.http.routers.authentication-prod.tls.certresolver: "letsencrypt"
      traefik.http.services.authentication-prod.loadbalancer.server.port: "8080"
      traefik.http.middlewares.authentication-prod-strip.stripprefix.prefixes: "/api/auth"
      traefik.http.routers.authentication-prod.middlewares: "authentication-prod-strip"

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true